spring.application.name=appointment-service
server.port = 8082

spring.datasource.url=jdbc:h2:mem:appointmentdb
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.Dialect
spring.h2.console.enabled=true
